package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserMoney;
import org.linlinjava.litemall.db.domain.LitemallUserMoneyExample;

public interface LitemallUserMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int insert(LitemallUserMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    LitemallUserMoney selectOneByExample(LitemallUserMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    LitemallUserMoney selectOneByExampleSelective(@Param("example") LitemallUserMoneyExample example, @Param("selective") LitemallUserMoney.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    List<LitemallUserMoney> selectByExampleSelective(@Param("example") LitemallUserMoneyExample example, @Param("selective") LitemallUserMoney.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    List<LitemallUserMoney> selectByExample(LitemallUserMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    LitemallUserMoney selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserMoney.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    LitemallUserMoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserMoney record, @Param("example") LitemallUserMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserMoney record, @Param("example") LitemallUserMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserMoney record);
}