package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserMoneyHistory;
import org.linlinjava.litemall.db.domain.LitemallUserMoneyHistoryExample;

public interface LitemallUserMoneyHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserMoneyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserMoneyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int insert(LitemallUserMoneyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserMoneyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    LitemallUserMoneyHistory selectOneByExample(LitemallUserMoneyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    LitemallUserMoneyHistory selectOneByExampleSelective(@Param("example") LitemallUserMoneyHistoryExample example, @Param("selective") LitemallUserMoneyHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    List<LitemallUserMoneyHistory> selectByExampleSelective(@Param("example") LitemallUserMoneyHistoryExample example, @Param("selective") LitemallUserMoneyHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    List<LitemallUserMoneyHistory> selectByExample(LitemallUserMoneyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    LitemallUserMoneyHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserMoneyHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    LitemallUserMoneyHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserMoneyHistory record, @Param("example") LitemallUserMoneyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserMoneyHistory record, @Param("example") LitemallUserMoneyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserMoneyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_money_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserMoneyHistory record);
}