package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallScoreRule;
import org.linlinjava.litemall.db.domain.LitemallScoreRuleExample;

public interface LitemallScoreRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    long countByExample(LitemallScoreRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallScoreRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int insert(LitemallScoreRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int insertSelective(LitemallScoreRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    LitemallScoreRule selectOneByExample(LitemallScoreRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    LitemallScoreRule selectOneByExampleSelective(@Param("example") LitemallScoreRuleExample example, @Param("selective") LitemallScoreRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    List<LitemallScoreRule> selectByExampleSelective(@Param("example") LitemallScoreRuleExample example, @Param("selective") LitemallScoreRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    List<LitemallScoreRule> selectByExample(LitemallScoreRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    LitemallScoreRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallScoreRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    LitemallScoreRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallScoreRule record, @Param("example") LitemallScoreRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallScoreRule record, @Param("example") LitemallScoreRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallScoreRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallScoreRule record);
}