package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserFriend;
import org.linlinjava.litemall.db.domain.LitemallUserFriendExample;

public interface LitemallUserFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int insert(LitemallUserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    LitemallUserFriend selectOneByExample(LitemallUserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    LitemallUserFriend selectOneByExampleSelective(@Param("example") LitemallUserFriendExample example, @Param("selective") LitemallUserFriend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    List<LitemallUserFriend> selectByExampleSelective(@Param("example") LitemallUserFriendExample example, @Param("selective") LitemallUserFriend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    List<LitemallUserFriend> selectByExample(LitemallUserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    LitemallUserFriend selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserFriend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    LitemallUserFriend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserFriend record, @Param("example") LitemallUserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserFriend record, @Param("example") LitemallUserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserFriend record);
}