package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallScore;
import org.linlinjava.litemall.db.domain.LitemallScoreExample;

public interface LitemallScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    long countByExample(LitemallScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int insert(LitemallScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int insertSelective(LitemallScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    LitemallScore selectOneByExample(LitemallScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    LitemallScore selectOneByExampleSelective(@Param("example") LitemallScoreExample example, @Param("selective") LitemallScore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    List<LitemallScore> selectByExampleSelective(@Param("example") LitemallScoreExample example, @Param("selective") LitemallScore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    List<LitemallScore> selectByExample(LitemallScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    LitemallScore selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallScore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    LitemallScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallScore record, @Param("example") LitemallScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallScore record, @Param("example") LitemallScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallScore record);
}